### ISSUE TITLE
Practica del modulo 2: listado de clientes segun paridad

### ISSUE THREAD

**Issue by dragonnegro78** [leamarty/cursoweb#13]
Al poner buscar, mando 1 solo request al server de Lea (url abajo)
El response devuelve success o error. Si dice error, no hacer ningun request mas. Lo unico que se puede hacer es volver a poner el boton buscar y empezar de nuevo. (poner el texto del boton, o un popup q diga "intente nuevamente en unos segundos")
Si response success, hacer por paralelo 2 requests por 10 clientes (5 pares y 5 impares).
La respuesta la manejamos nosotros desde PHP (no el server de lea) y la respuesta de los impares tiene que tener un sleep(3) (en PHP).
En el front-end, todo se dibuja apenas llega.

Al enviar el primer request, bloquer el boton hasta saber si estamos autorizados o no.
Si no estamos autorizados, permitir que se presione el boton inmediatamente para buscar de vuelta si estamos autorizados ahora o no.
Si estamos autorizados, mandar inmediatamente los 2 requests nuevos y mantener el boton bloqueado hasta que vuelva el ultimo response.

Server que autoriza: ccvalsina.com/cursoweb/autorizacion.php

Php ejemplo: ccvalsina.com/cursoweb/clientes.php
parametros: desde, cantidad, filtro
ej
clientes.php?desde=2&cantidad=10&filtro=impar

**Comment by leamarty** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/3124547/11017490/7e21a254-857f-11e5-80ea-88c02df59d24.png)
![sin titulo1](https://cloud.githubusercontent.com/assets/3124547/11017507/bd81688a-857f-11e5-9147-5d3af34af121.png)
![sin titulo2](https://cloud.githubusercontent.com/assets/3124547/11017491/80aa7528-857f-11e5-9b15-ea96ba635d80.png)
![sin titulo3](https://cloud.githubusercontent.com/assets/3124547/11017494/83da8508-857f-11e5-9ff1-260687f04c1d.png)

**Comment by dragonnegro78** [comment]
solucionado con https://github.com/leamarty/cursoweb/commit/e6d8fb2923934d4ab6b882fac269619f2a76e64e
