### ISSUE TITLE
Practica del modulo 3: listado de clientes con mysql y hacemos que clientes sea RESTful

### ISSUE THREAD

**Issue by dragonnegro78** [leamarty/cursoweb#17]
Hacer un script en php para convertir clientes.json e insertarlo en mysql.

La query de MySQL tiene que traer de a 5 pares, no a los clientes pares entre 1 y 10 por ejemplo.
La query de MySQL tiene que traer los 5 pares de una, no tenemos que hacer 5 queries. (1 SELECT que traiga los 5)

clientes.php tiene que ser RESTful (salvo la parte de redireccionar segun la url):
 · implementar GET, POST y DELETE.
 · cuando hace DELETE, tiene que tener un sleep(2). cuando hace DELETE, bloquear el boton que se apretó hasta que vuelva el ajax.

En el listado de clientes (en index), agregar una columna que sea para borrar el cliente en esa fila (de la vista y de mysql). El ajax que envia a clientes.php tiene que tener DELETE como verbo.

Agregar nueva pestaña para cargar un nuevo cliente (ver fotos de lea debajo).

16/11: cuando pido los clientes desde php a mysql, al traerlos, guardar cada cliente (en php) como una clase Cliente instanciada por cada cliente que traigo, y luego convertir la clase en json al enviarla al index que lo pidio por ajax.

17/11: la clase Cliente en clientes.php tiene que tener los metodos borrar (llamada desde DELETE) y guardar (llamada desde POST) y estos metodos deben conectarse con la DB y realizar las queries correspondientes.

**Comment by dragonnegro78** [comment]
@alvarezhm a laburar

**Comment by dragonnegro78** [comment]
@leamarty y los screenshots?

**Comment by dragonnegro78** [comment]
@leamarty creo que copie algo mal en el enunciado del issue. Puede ser que haya que implementar GET PUT DELETE pero NO haya que hacerla restful porque dijiste que no nos ibamos a meter con eso hasta que pasemos a laravel porque nos facilitaba el tema de los htaccess?

**Comment by leamarty** [comment]
Claro, hay que hacerlo con GET POST y DELETE (no PUT, no tenemos update), pero que todos le peguen al archivo clientes.php, y en el caso del delete mandar {id: id_cliente} en la data.

La onda es acercarnos a los RESTful, sin llegar todavía a hacerlo full full.

**Comment by leamarty** [comment]
Van los screenshots. Tengan en cuenta que ninguno de los campos puede ser nulo o vacío. Esto hay que restringirlo por base de datos y también chequearlo en PHP y en HTML (es decir, en casi todos lados, menos en JS).

![sin titulo](https://cloud.githubusercontent.com/assets/3124547/11182504/13ef6656-8c4a-11e5-92a4-6aa705f42d27.png)

![sin titulo1](https://cloud.githubusercontent.com/assets/3124547/11182505/1551bf76-8c4a-11e5-9ae1-a1f8e6fb63ba.png)

**Comment by dragonnegro78** [comment]
@ToadMaster  @alvarezhm  actualice el post principal del issue, agregue el ultimo parrafo y lo que dice que DELETE tiene que ser un verbo.

**Comment by dragonnegro78** [comment]
@alvarezhm @ToadMaster actualice el OP. Agregue solo la parte correspondiente al 17/11
