### ISSUE TITLE
POST TP 3 502 BAD GATEWAY

### ISSUE THREAD

**Issue by GustavoBilzBorre** [leamarty/cursoweb#19]
¿Lea, le podés pegar una mirada al index de mi push que me tira el error ése? Me fijé el action y tiene el mismo nombre que el clientes.php

**Comment by dragonnegro78** [comment]
Me baje tu branch y la ejecute, me borro un cliente perfectamente. Tenes algun problema en tu sistema de apache/php/mysql que te esta tirando ese error.
![untitled](https://cloud.githubusercontent.com/assets/15573422/11450093/519fa3b6-956f-11e5-8a8b-56a19017f01f.png)
