### ISSUE TITLE
Práctica del módulo 1: listado de clientes de Telapong S.A.

### ISSUE THREAD

**Issue by leamarty** [leamarty/cursoweb#8]
![sin titulo2](https://cloud.githubusercontent.com/assets/3124547/10871644/9cb6b834-80cb-11e5-8c0c-ea4db01d4f95.png)

![sin titulo](https://cloud.githubusercontent.com/assets/3124547/10871646/9fb259c6-80cb-11e5-8736-8cb4951af9d9.png)

**Comment by leamarty** [comment]
@ToadMaster @alvarezhm

**Comment by dragonnegro78** [comment]
Resuelto al hacer el commit a master por @leamarty 
en https://github.com/leamarty/cursoweb/commit/2697a21ffc293e54e1e819863fc0fe05324c32b3
